package com.azxca1731.member.common;

public enum Code {
    VERIFY_SUCCESS,
    SIGN_UP_SUCCESS,
    SIGN_OUT_SUCCESS,

    COMMON_FAIL,
    VERIFY_VALIDATION_REJECT,
    VERIFY_PROVIDER_REJECT,

    SIGN_UP_VALIDATION_REJECT,

    SIGN_OUT_NOT_CHANGED_REJECT,
    SIGN_OUT_VALIDATION_REJECT
}
