spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test_user
    password: password1111
  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8070